name: e2e-test

on:
  push:
  schedule:
    # JST で毎週土曜 12:00 (UTC で毎週土曜 3:00) に実行
    - cron: '0 3 * * SAT'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - uses: microsoft/playwright-github-action@v1

      - uses: actions/cache@v2
        with:
          path: ${YARN_CACHE_FOLDER}
          key: ${{ runner.os }}-yarn-cache-v1
      - run: yarn install --frozen-lockfile

      - run: yarn run build

      # playwright を headful モードで起動しないと E2E テストが動かないので、xvfb-run を使い、playwright を headful モードで起動する
      # ref: https://github.com/microsoft/playwright-github-action#run-in-headful-mode
      - name: yarn run test
        run: xvfb-run --auto-servernum -- yarn run test

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: e2e-dist
          path: |
            e2e-dist
            e2e-test/**/__image_snapshots__/__diff_output__

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ github.event_name == 'schedule' && always() }}
